###
GET http://localhost:5002/v1/test

###
POST http://localhost:5002/v1/test/db
Content-Type: application/json

{
  "name": "First Mongo Test",
  "message": "Checking if data is saved",
  "source": "postman"
}

###
GET http://localhost:5002/v1/test/db
