const Airtable = require("airtable");
const httpStatus = require("http-status");
const config = require("../config/config");
const ApiError = require("../utils/ApiError");

// Initialize Airtable
const base = new Airtable({ apiKey: config.airtable.apiKey }).base(
  config.airtable.baseId
);

/**
 * DEPRECATED: This function should NOT be used anymore
 * Confirmation numbers are now generated ONLY by the Booking model
 * to ensure uniqueness and consistency across MongoDB and Airtable
 *
 * @deprecated Use the booking's confirmationNumber from MongoDB instead
 * @returns {string} Generated confirmation number
 */
const generateConfirmationNumber = () => {
  console.warn("WARNING: generateConfirmationNumber() in airtable.service is deprecated. Use booking's confirmationNumber instead.");
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  // Changed to 4-digit suffix to match booking model
  const randomSuffix = Math.floor(Math.random() * 10000)
    .toString()
    .padStart(4, "0");

  return `BRG-${year}${month}${day}-${randomSuffix}`;
};

/**
 * Map contentType values from booking model to valid Airtable options
 * @param {string|Array} contentType - Content type from booking
 * @returns {string} Valid Airtable content type value
 */
const mapContentTypeToAirtable = (contentType) => {
  // Handle array case
  if (Array.isArray(contentType)) {
    contentType = contentType.join(", ");
  }

  // Map booking model values to Airtable valid options
  // Airtable only accepts: 'videography', 'photography', or 'both'
  const contentTypeMapping = {
    photo: "photography",
    video: "videography",
    edit: "photography", // Default editing to photography
    all: "both",
    photography: "photography",
    videography: "videography",
    editing: "photography", // Default editing to photography
  };

  // Convert to lowercase for mapping, handle multiple values
  const types = contentType
    .toLowerCase()
    .split(/[,&\s]+/)
    .map((type) => type.trim())
    .filter((type) => type && type !== "");

  // If multiple types include both photo/photography and video/videography, return 'both'
  const hasPhoto = types.some((type) =>
    ["photo", "photography"].includes(type)
  );
  const hasVideo = types.some((type) =>
    ["video", "videography"].includes(type)
  );

  if (hasPhoto && hasVideo) {
    return "both";
  }

  // Otherwise map the first valid type
  for (const type of types) {
    if (contentTypeMapping[type]) {
      return contentTypeMapping[type];
    }
  }

  return "photography"; // Default fallback
};

/**
 * Map booking data to Airtable fields based on booking-flow-designs.pdf and payment-screens.pdf
 * @param {Object} bookingData - Booking data from Stripe
 * @param {Object} paymentData - Payment data from Stripe
 * @param {string} confirmationNumber - REQUIRED confirmation number from booking (must be provided)
 * @returns {Object} Mapped Airtable fields
 */
const mapBookingToAirtableFields = (bookingData, paymentData, confirmationNumber) => {
  // CRITICAL: Confirmation number MUST be provided from MongoDB booking
  // Never generate it here to avoid duplicates and inconsistencies
  if (!confirmationNumber) {
    throw new ApiError(
      httpStatus.INTERNAL_SERVER_ERROR,
      "Confirmation number is required for Airtable sync. It must be generated by the Booking model."
    );
  }

  return {
    // Core fields that we know work
    "Guest Name": bookingData.guestName,
    "Guest Email": bookingData.guestEmail,
    "Content Type": mapContentTypeToAirtable(bookingData.contentType),
    Status: "paid",
    "Confirmation Number": confirmationNumber,

    // Try additional fields one by one
    ...(bookingData.guestPhone && { "Guest Phone": bookingData.guestPhone }),
    ...(bookingData.shootType && { "Shoot Type": bookingData.shootType }),
    ...(bookingData.editType && { "Edit Type": bookingData.editType }),
    ...(bookingData.durationHours && {
      "Duration (Hours)": parseInt(bookingData.durationHours),
    }),
    ...(bookingData.location && { Location: bookingData.location }),
    // Include Payment Amount even if it's 0 (for free bookings)
    ...(paymentData.totalAmount !== undefined && paymentData.totalAmount !== null && {
      "Payment Amount": parseFloat(paymentData.totalAmount),
    }),
  };
};

/**
 * Create a booking record in Airtable
 * @param {Object} bookingData - Booking data from form
 * @param {Object} paymentData - Payment data from Stripe
 * @param {string} confirmationNumber - REQUIRED confirmation number from MongoDB booking
 * @returns {Promise<Object>} Created Airtable record
 */
const createBookingRecord = async (bookingData, paymentData, confirmationNumber) => {
  // Validate that confirmation number is provided
  if (!confirmationNumber) {
    throw new ApiError(
      httpStatus.INTERNAL_SERVER_ERROR,
      "Confirmation number must be provided from MongoDB booking before syncing to Airtable"
    );
  }
  try {
    if (!config.airtable.apiKey || !config.airtable.baseId) {
      throw new ApiError(
        httpStatus.INTERNAL_SERVER_ERROR,
        "Airtable configuration is missing"
      );
    }

    const fields = mapBookingToAirtableFields(bookingData, paymentData, confirmationNumber);

    const record = await base(config.airtable.tableName).create([
      {
        fields,
      },
    ]);

    if (!record || record.length === 0) {
      throw new ApiError(
        httpStatus.INTERNAL_SERVER_ERROR,
        "Failed to create Airtable record"
      );
    }

    return {
      airtableId: record[0].id,
      confirmationNumber: fields["Confirmation Number"],
      fields: record[0].fields,
    };
  } catch (error) {
    console.error("Airtable creation error:", error);
    throw new ApiError(
      httpStatus.INTERNAL_SERVER_ERROR,
      `Failed to create booking in Airtable: ${error.message}`
    );
  }
};

/**
 * Update booking status in Airtable
 * @param {string} airtableId - Airtable record ID
 * @param {string} status - New status (paid, assigned, completed)
 * @param {Object} updates - Additional fields to update
 * @returns {Promise<Object>} Updated Airtable record
 */
const updateBookingStatus = async (airtableId, status, updates = {}) => {
  try {
    const fieldsToUpdate = {
      Status: status,
      ...updates,
    };

    const record = await base(config.airtable.tableName).update([
      {
        id: airtableId,
        fields: fieldsToUpdate,
      },
    ]);

    return record[0];
  } catch (error) {
    console.error("Airtable update error:", error);
    throw new ApiError(
      httpStatus.INTERNAL_SERVER_ERROR,
      `Failed to update booking in Airtable: ${error.message}`
    );
  }
};

/**
 * Get booking record from Airtable
 * @param {string} airtableId - Airtable record ID
 * @returns {Promise<Object>} Airtable record
 */
const getBookingRecord = async (airtableId) => {
  try {
    const record = await base(config.airtable.tableName).find(airtableId);
    return record;
  } catch (error) {
    console.error("Airtable retrieval error:", error);
    throw new ApiError(
      httpStatus.NOT_FOUND,
      `Failed to retrieve booking from Airtable: ${error.message}`
    );
  }
};

/**
 * Get all bookings with a specific status for ops team
 * @param {string} status - Status to filter by (paid, assigned, completed)
 * @param {number} maxRecords - Maximum number of records to return
 * @returns {Promise<Array>} Array of booking records
 */
const getBookingsByStatus = async (status = "paid", maxRecords = 100) => {
  try {
    const records = await base(config.airtable.tableName)
      .select({
        filterByFormula: `{Status} = '${status}'`,
        maxRecords,
        // Remove sorting for now since we don't know which date field exists
      })
      .all();

    return records.map((record) => ({
      airtableId: record.id,
      ...record.fields,
    }));
  } catch (error) {
    console.error("Airtable query error:", error);
    throw new ApiError(
      httpStatus.INTERNAL_SERVER_ERROR,
      `Failed to retrieve bookings from Airtable: ${error.message}`
    );
  }
};

/**
 * Create booking from Stripe payment success
 * Handles both checkout session and payment intent data
 * @param {Object} stripeData - Stripe session or payment intent data
 * @returns {Promise<Object>} Created booking record
 */
const createBookingFromPayment = async (stripeData) => {
  try {
    let bookingData, paymentData;

    // Handle Stripe checkout session
    if (stripeData.object === "checkout.session") {
      const metadata = stripeData.metadata;
      if (!metadata.bookingData) {
        throw new Error("Booking data not found in checkout session metadata");
      }
      bookingData = JSON.parse(metadata.bookingData);
      paymentData = {
        transactionId: stripeData.payment_intent,
        stripeSessionId: stripeData.id,
        paymentIntentId: stripeData.payment_intent,
        totalAmount: metadata.totalAmount,
        basePrice: metadata.basePrice,
        discount: metadata.discount,
        userId: metadata.userId,
      };
    }
    // Handle Stripe payment intent
    else if (stripeData.object === "payment_intent") {
      const metadata = stripeData.metadata;
      if (!metadata.bookingData) {
        throw new Error("Booking data not found in payment intent metadata");
      }
      bookingData = JSON.parse(metadata.bookingData);
      paymentData = {
        transactionId: stripeData.id,
        paymentIntentId: stripeData.id,
        totalAmount: metadata.totalAmount,
        basePrice: metadata.basePrice,
        discount: metadata.discount,
        userId: metadata.userId,
      };
    } else {
      throw new ApiError(
        httpStatus.BAD_REQUEST,
        "Invalid Stripe data object type"
      );
    }

    // Create the booking record in Airtable
    const airtableRecord = await createBookingRecord(bookingData, paymentData);

    console.log(
      `Booking created in Airtable: ${airtableRecord.confirmationNumber}`
    );

    return airtableRecord;
  } catch (error) {
    console.error("Error creating booking from payment:", error);
    throw error;
  }
};

module.exports = {
  createBookingRecord,
  updateBookingStatus,
  getBookingRecord,
  getBookingsByStatus,
  createBookingFromPayment,
  generateConfirmationNumber,
  mapBookingToAirtableFields,
};
